### PR TITLE
feat(import): social list

### PR DESCRIPTION
**Pull request by kptdobe**
Fix for #48

### CODE REVIEW

**Comment by kptdobe** [comment]
Results look like this:

```
Social:

-   [facebook](https://www.facebook.com/CreativeProWeek/)
-   [twitter](https://twitter.com/creativeproweek)
-   [linkedin](https://www.linkedin.com/in/davidblatner/)
```

**Comment by kptdobe** [comment]
@rofe The clientside handling does not work. I assume the line break is the issue but it comes for free in the html to md transformation :) I think it is common practice to have an empty line before a list...

**Comment by rofe** [comment]
The client side expects the link href and link text to be the same (the URL), see also https://github.com/adobe/helix-theblog-importer/issues/48#issuecomment-642066014

**Comment by kptdobe** [comment]
ah ok... miss-understood :)

**Comment by kptdobe** [comment]
ok, the link format is weird (seems to be the default when transforming a link where href = content): 

```
Social:

-   <https://www.facebook.com/CreativeProWeek/>
-   <https://twitter.com/creativeproweek>
-   <https://www.linkedin.com/in/davidblatner/>
```

but it works as expected: https://theblog-adobe.hlx.page/en/authors/david-blatner.html

**Comment by rofe** [comment]
I was expecting the social links to get picked up and rendered correctly... will revisit the client side code tomorrow.

**Comment by rofe** [comment]
Forget what I said, it was a caching issue: everything is working as expected! 😅

**Pull request merged**
